### ISSUE TITLE
Faire marcher les tests de bases

### ISSUE THREAD

**Issue by Floki** [Floki/cookeat#14]
Essayer de faire marcher tous les tests auto généré qu ne marche pas.

**Comment by skaboy** [comment]
Ok, quand j'ai vu le push, j'avais pas vu que c'était des test auto généré.

**Comment by Floki** [comment]
Bon, j'ai ai passé une paire d'heures ce soir et j'ai pas avancé.

Les choses à savoir : 
  Toutes les erreurs arrivent sur les test des controller, à trois endroits, les mêmes dans chaque classe de test
  J'ai essayé de faire des recherches sur l'une d'entre elles : CannotRedirectException qui arrive lors de l'utilisation d'un redirect dans les méthodes save des controller, rien trouvé du tout sur notre ami Google.
 Du coup j'ai eut l'idée de vérifier si le prof utilisait des test autogénérés dans tsaap note, la réponse est oui, et il a presque exactement le même type de controller et type de test que nous. J'ai donc cloné le project de tsaap note, et tous les tests passent niquel sur ma machine. 

Résultat, j'ai deux idées, soit on a un problème de conf, soit c'est les quelques différences dans la classe du controlleur qui comptes.

J'ai essayé plusieurs truc pour la conf, rien de probant (passage a grails 2.3.4, changement des versions des plugins, etc....)..

Et là je viens d'essayer de rajouter les quelques lignes dont dispose la controller en plus par rapport à nos controller, mais mon Eclipse veut plus rien savoir et me sort des erreurs incompréhensible de partout. :(

Du coup, j'en ai marre, et je réessayerai plus tard dans la semaine si personne n'a trouvé un truc d'ici là.

Bonne soirée!

Note : Pour comparé, allez voir les classes :
Tsaap :
https://github.com/TSaaP/tsaap-notes/blob/develop/grails-app/controllers/org/tsaap/notes/ContextController.groovy
Cookeat :
https://github.com/Floki/cookeat/blob/master/grails-app/controllers/cookeat/recipe/CommentController.groovy

Et les tests : 
Tsaap :
https://github.com/TSaaP/tsaap-notes/blob/develop/test/unit/org/tsaap/notes/ContextControllerSpec.groovy
Cookeat :
https://github.com/Floki/cookeat/blob/master/test/unit/cookeat/recipe/CommentControllerSpec.groovy

Il y a des différences notamment dans le controller, genre des annotation en plus en rapport avec springsecurity, après, le problèmes bient t'il de là...

**Comment by Floki** [comment]
Juste pour être sur quand même, suis je le seul a avoir des soucis avec les test autogénéré des controllers qui passe pas? Apparemment, Robin tu en as aussi si j'ai bien compris.

**Comment by Floki** [comment]
Trouvé!

Ca vient de plusieurs truc : 
1 : Il faut remplir la méthode populateValidParams de chaque cas de test de controller avec des paramètres valides
2 : Il restait un petit réglage à faire pour spring security dans conf/spring/ressource
3 : Il faut rajouter un attribut SpringSecurityService springSecurityService = Mock(SpringSecurityService) dans les classe de test de controller
4 : Avant de save une classe du domain, penser à lui attribuer le service spring security de la classe de test

J'ai essayé avec la test UsercontrollerSpec, tous les test passent sauf un où la redirection foire. Il faudra faire ça pour tous les controller dont on aura besoin .

Je commit tout ce basar.
Bonne soirée!

**Comment by exasky** [comment]
GG!
