### ISSUE TITLE
IHM - Commentaires

### ISSUE THREAD

**Issue by exasky** [Floki/cookeat#21]

**Comment by Floki** [comment]
Fait pour l'ajout et le listage sur une recette.
(j'espère avoir rien péter après le merge, je sais pas pourquoi git m'a fait un conflit sur les fichier User alors que j'y ai pas touché).

**Comment by exasky** [comment]
GG ça marche ;) maintenant faudrait que tu puisses supprimer le commentaire, et que tu fasses les tests sur le controller :)

**Comment by Floki** [comment]
Yo, je suis fasse à un p****\* de bug que j'arrive pas à rédoudre : 
J'ai ajouter de quoi supprimer un commentaires. Si j'appelle la méthode de comment service, le commentaire ne se supprime pas, si je change la fonction en comment.delete(flush: true) j'ai un illegalStateException qui apparait sur toutes les pages. T'as déjà eut ce problème? C'est légerement en train de me saouler là. xD

**Comment by Floki** [comment]
Bon j'ai rien fait, mais ça arrive plus, pas compris. J'écris les test et j'envoie et ça sera bon pour aujourd'hui.

**Comment by exasky** [comment]
Je suis aussi en train de faire le delete sur les comments ^^tu t'en occupe alors?

**Comment by exasky** [comment]
By the way, quand tu ajoutes un commentaire, il ne s'ajoute pas à l'utilisateur ^^je m'occupe de ça

**Comment by exasky** [comment]
C'est parfait tout ça !!!!! Bon par contre gros soucis, on est passés en dessous des 70% de coverage :/

**Comment by exasky** [comment]
Corrigé, on est repassé à plus de 80% haha
