### ISSUE TITLE
PPT : Présentation

### ISSUE THREAD

**Issue by Floki** [Floki/cookeat#24]
https://docs.google.com/presentation/d/1riQht5w8429FTLS6Qo3nHgAgg2QYj5cP40zxFfwtB-E/edit?usp=sharing

**Comment by Floki** [comment]
Mise à jour du thème.

**Comment by exasky** [comment]
On pourra pas faire de démo, du coup faut des print_screen ;) (sauf si évidemment on peut déployer l'app ^^)
