### ISSUE TITLE
DOC : Documentation du projet

### ISSUE THREAD

**Issue by Floki** [Floki/cookeat#25]
Lien google doc : 
https://docs.google.com/document/d/1upUVKHlXHFYP_LXlJjiLyRnDcTnDnLYxfio-XrCI9lg/edit

Je vais faire au mieux pour y bosser dans la journée, mais on est un petit peu débordé au boulot de mon coté (en dehors de la FAC). :/  

Ca fait quand même 5 points de la notes du projet.

Planning de M****!

**Comment by exasky** [comment]
Ouaip faut s'y attaquer, Ismail, Robin? On est chauds? :D

**Comment by Floki** [comment]
Merci, je viens d'apprendre que la livraison à mon boulot a été avancé à demain soir, va falloir que je bosse à fond aujourd'hui. xD

J'essayerai de faire des passes de temps en temps. ^^

**Comment by exasky** [comment]
Cha marche ^^, faut tous s'y mettre t'façon ;) Mais déjà un gros GG pour le travail que t'as commencé :)
