### ISSUE TITLE
Créer une recette

### ISSUE THREAD

**Issue by exasky** [Floki/cookeat#6]

**Comment by exasky** [comment]
Et l'ajouter à un thème

**Comment by smailGithub** [comment]
Je continue le CRUD Recipe ?! @exasky @Floki @skaboy 
C'est ok pour toi @exasky ?

**Comment by exasky** [comment]
Fais toi plaisir ;)

Cordialement,
M. Simar Jérémy

**Comment by exasky** [comment]
Pense juste à commit les tests en même temps ;)

**Comment by smailGithub** [comment]
Tkt , je suis sur les test d'intégration là 
Apres on pourra fermer l'issue

**Comment by smailGithub** [comment]
Test integration sur delete recipe à venir demain !
